=== PROXIES FUNCIONANDO ===
http 37.120.172.84:80
http 99.79.124.70:80
http 89.58.53.205:80

=== PROXIES FALLIDOS ===
http 51.75.206.209:80 - Razón: HTTPConnectionPool(host='51.75.206.209', port=80): Max retries exceeded with url: http://httpbin.org/ip (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001793072E960>, 'Connection to 51.75.206.209 timed out. (connect timeout=10)')))
http 50.223.246.237:80 - Razón: HTTPConnectionPool(host='50.223.246.237', port=80): Max retries exceeded with url: http://httpbin.org/ip (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001793072C470>, 'Connection to 50.223.246.237 timed out. (connect timeout=10)')))
http 50.174.7.159:80 - Razón: HTTPConnectionPool(host='50.174.7.159', port=80): Max retries exceeded with url: http://httpbin.org/ip (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001793072F680>, 'Connection to 50.174.7.159 timed out. (connect timeout=10)')))
http 50.207.199.87:80 - Razón: HTTPConnectionPool(host='50.207.199.87', port=80): Max retries exceeded with url: http://httpbin.org/ip (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001793072F350>, 'Connection to 50.207.199.87 timed out. (connect timeout=10)')))
http 32.223.6.94:80 - Razón: HTTPConnectionPool(host='32.223.6.94', port=80): Max retries exceeded with url: http://httpbin.org/ip (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001793072EEA0>, 'Connection to 32.223.6.94 timed out. (connect timeout=10)')))
http 50.207.199.80:80 - Razón: HTTPConnectionPool(host='50.207.199.80', port=80): Max retries exceeded with url: http://httpbin.org/ip (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001793072FC50>, 'Connection to 50.207.199.80 timed out. (connect timeout=10)')))
http 50.207.199.83:80 - Razón: HTTPConnectionPool(host='50.207.199.83', port=80): Max retries exceeded with url: http://httpbin.org/ip (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000179307581A0>, 'Connection to 50.207.199.83 timed out. (connect timeout=10)')))
http 50.174.7.153:80 - Razón: HTTPConnectionPool(host='50.174.7.153', port=80): Max retries exceeded with url: http://httpbin.org/ip (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000017930758C20>, 'Connection to 50.174.7.153 timed out. (connect timeout=10)')))
http 50.202.75.26:80 - Razón: HTTPConnectionPool(host='50.202.75.26', port=80): Max retries exceeded with url: http://httpbin.org/ip (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001793072FE30>, 'Connection to 50.202.75.26 timed out. (connect timeout=10)')))
http 50.239.72.18:80 - Razón: HTTPConnectionPool(host='50.239.72.18', port=80): Max retries exceeded with url: http://httpbin.org/ip (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001793072EFC0>, 'Connection to 50.239.72.18 timed out. (connect timeout=10)')))
http 50.175.212.66:80 - Razón: HTTPConnectionPool(host='50.175.212.66', port=80): Max retries exceeded with url: http://httpbin.org/ip (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001793072ECF0>, 'Connection to 50.175.212.66 timed out. (connect timeout=10)')))
http 50.217.226.47:80 - Razón: HTTPConnectionPool(host='50.217.226.47', port=80): Max retries exceeded with url: http://httpbin.org/ip (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000017930758BF0>, 'Connection to 50.217.226.47 timed out. (connect timeout=10)')))
http 50.239.72.16:80 - Razón: HTTPConnectionPool(host='50.239.72.16', port=80): Max retries exceeded with url: http://httpbin.org/ip (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000017930758770>, 'Connection to 50.239.72.16 timed out. (connect timeout=10)')))
http 50.239.72.19:80 - Razón: HTTPConnectionPool(host='50.239.72.19', port=80): Max retries exceeded with url: http://httpbin.org/ip (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000017930759BB0>, 'Connection to 50.239.72.19 timed out. (connect timeout=10)')))
http 50.217.226.40:80 - Razón: HTTPConnectionPool(host='50.217.226.40', port=80): Max retries exceeded with url: http://httpbin.org/ip (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001793072F710>, 'Connection to 50.217.226.40 timed out. (connect timeout=10)')))
http 50.221.74.130:80 - Razón: HTTPConnectionPool(host='50.221.74.130', port=80): Max retries exceeded with url: http://httpbin.org/ip (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001793072FC50>, 'Connection to 50.221.74.130 timed out. (connect timeout=10)')))
